
version: "3"
volumes:
    wp:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/mix/data/wp
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/mix/data/db

networks:
    new_network:
        driver: bridge

services:
    mariadb:
        volumes:
          - db:/var/lib/mysql
        restart: always
        build:
          context: MariaDB/
          args:
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          WORDPRESS_WEBSITE_URL_WITHOUT_HTTP: ${WORDPRESS_WEBSITE_URL_WITHOUT_HTTP}
          WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
          WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
          WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_PASSWORD}
        image: mariadb
        networks:
          - new_network
        container_name: mariadb
    nginx:
        volumes:
          - wp:/var/www/html
        depends_on:
          - wordpress
        ports:
            - "443:443"
        env_file: .env
        restart: always
        build: nginx
        image: nginx
        networks:
          - new_network
        container_name: nginx
    wordpress:
        depends_on:
          - mariadb
        restart: always
        build:
          context: WordPress
          args:
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        volumes:
          - wp:/var/www/html
        environment:
          WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
          WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
          WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
          WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        image: wordpress
        networks:
          - new_network
        container_name: wordpress
