
mkdir:
	mkdir -p /home/mix/data/wp
	mkdir -p /home/mix/data/db

up:
	docker-compose -f srcs/docker-compose.yml up
down:
	docker-compose -f srcs/docker-compose.yml down
re:
	docker-compose -f srcs/docker-compose.yml up --build
ps:
	docker-compose -f srcs/docker-compose.yml ps

